/* ═══════════════════════════════════════════════════════════
   Lesson 23 — Goethe Zertifikat A2 Hören
   Источник: YouTube
   ═══════════════════════════════════════════════════════════ */

var LESSONS = window.LESSONS || [];

var LESSON_23 = {
  id: 'lesson-23',
  number: 23,
  title: 'Goethe A2 Hören — Modelltest',
  subtitle: 'Dieser Prüfungsteil hat vier Teile: Kurze Texte, Gespräch, Kurze Gespräche und Interview',
  level: 'A2',
  source: 'Goethe-Institut',
  videoId: 'Vid-23',
  videoUrl: 'https://www.youtube.com/watch?v=FRRq_hPXins',

  /* ─── 12 мини-текстов по частям ─── */
  texts: [
    /* ═══ TEIL 1 — 5 коротких текстов ═══ */
    {
      id: 'text-1', teil: 1, aufgabe: 1,
      name: 'Anna',
      type: 'телефонное сообщение',
      text: 'Hallo, hier ist Anna. Geht es dir? Ich will dich zu mir nach Hause einladen. Ich möchte dir nämlich mein neues Zimmer zeigen. Es ist nicht sehr groß und auch nicht neu, aber hell und gemütlich. Mein altes Zimmer war groß, aber ich musste das mit meiner Schwester teilen. Kannst du morgen Nachmittag um 5 Uhr? Melde dich, tschüss.',
      sentenceTranslations: {
        'Hallo, hier ist Anna.': { literal: 'Привет, здесь есть Анна', literary: 'Привет, это Анна.' },
        'Geht es dir?': { literal: 'Идёт оно тебе?', literary: 'Как у тебя дела?' },
        'Ich will dich zu mir nach Hause einladen.': { literal: 'Я хочу тебя к себе домой пригласить', literary: 'Я хочу пригласить тебя к себе домой.' },
        'Ich möchte dir nämlich mein neues Zimmer zeigen.': { literal: 'Я хотела бы тебе именно мою новую комнату показать', literary: 'Я хочу показать тебе мою новую комнату.' },
        'Es ist nicht sehr groß und auch nicht neu, aber hell und gemütlich.': { literal: 'Она есть не очень большая и также не новая, но светлая и уютная', literary: 'Она не очень большая и не новая, но светлая и уютная.' },
        'Mein altes Zimmer war groß, aber ich musste das mit meiner Schwester teilen.': { literal: 'Моя старая комната была большая, но я должна была её с моей сестрой делить', literary: 'Моя старая комната была большая, но я должна была делить её с сестрой.' },
        'Kannst du morgen Nachmittag um 5 Uhr?': { literal: 'Можешь ты завтра послеобеденное-время в 5 часов?', literary: 'Можешь завтра в 5 часов дня?' },
        'Melde dich, tschüss.': { literal: 'Сообщи себя, пока', literary: 'Позвони мне, пока.' },
      },
      vocabulary: [
        { de: 'das Haus', plural: 'die Häuser', ru: 'дом', gender: 'neutrum', collocation: 'zu mir nach Hause einladen', example: 'Ich will dich zu mir nach Hause einladen.' },
        { de: 'das Zimmer', plural: 'die Zimmer', ru: 'комната', gender: 'neutrum', collocation: 'neues Zimmer zeigen', example: 'Ich möchte dir nämlich mein neues Zimmer zeigen.' },
        { de: 'die Schwester', plural: 'die Schwestern', ru: 'сестра', gender: 'feminin', collocation: 'mit meiner Schwester teilen', example: 'Ich musste das mit meiner Schwester teilen.' },
        { de: 'der Nachmittag', plural: 'die Nachmittage', ru: 'послеобеденное время', gender: 'maskulin', collocation: 'morgen Nachmittag', example: 'Kannst du morgen Nachmittag um 5 Uhr?' },
        { de: 'einladen', ru: 'приглашать', type: 'verb', forms: 'lädt ein, lud ein, hat eingeladen', example: 'Ich will dich zu mir nach Hause einladen.' },
        { de: 'zeigen', ru: 'показывать', type: 'verb', forms: 'zeigt, zeigte, hat gezeigt', example: 'Ich möchte dir nämlich mein neues Zimmer zeigen.' },
        { de: 'teilen', ru: 'делить', type: 'verb', forms: 'teilt, teilte, hat geteilt', example: 'Ich musste das mit meiner Schwester teilen.' },
        { de: 'sich melden', ru: 'связаться, позвонить', type: 'verb', forms: 'meldet sich, meldete sich, hat sich gemeldet', example: 'Melde dich, tschüss.' },
        { de: 'gemütlich', ru: 'уютный', type: 'adj', example: 'Es ist nicht sehr groß und auch nicht neu, aber hell und gemütlich.' },
        { de: 'hell', ru: 'светлый', type: 'adj', example: 'Es ist nicht sehr groß und auch nicht neu, aber hell und gemütlich.' },
      ],
      practiceSentences: [
        { de: 'Ich will dich ins Kino einladen.', ru: 'Я хочу пригласить тебя в кино.', note: 'модальный will + инфинитив' },
        { de: 'Sie möchte dir etwas zeigen.', ru: 'Она хочет тебе что-то показать.', note: 'möchte + инфинитив' },
        { de: 'Das Zimmer ist hell und groß.', ru: 'Комната светлая и большая.', note: 'ist на V2' },
        { de: 'Er muss sein Zimmer teilen.', ru: 'Он должен делить свою комнату.', note: 'muss + инфинитив' },
        { de: 'Melde dich bitte morgen!', ru: 'Позвони, пожалуйста, завтра!', note: 'императив с возвратным sich' },
      ],
      question: {
        de: 'Was möchte Anna zeigen?',
        ru: 'Что хочет показать Анна?',
        options: [
          { de: 'Ihr altes Zimmer', ru: 'Свою старую комнату' },
          { de: 'Ihr neues Zimmer', ru: 'Свою новую комнату' },
          { de: 'Ihre Schwester', ru: 'Свою сестру' },
        ],
        correct: 1,
        explanation: 'Анна говорит: "ich möchte dir nämlich mein neues Zimmer zeigen" — она хочет показать новую комнату.'
      }
    },
    {
      id: 'text-2', teil: 1, aufgabe: 2,
      name: 'Radio München',
      type: 'радиопередача',
      text: 'Hier ist Radio München, guten Morgen allerseits. Nach diesem fantastischen Wochenende wünsche ich euch allen einen wunderschönen Montagmorgen. Wir hatten am Samstag und Sonntag volles Programm. Konzerte, Theatervorstellungen und viele interessante Filme in den Kinos. Außerdem haben wir im Rock-Club verschiedene neue Bands vorgestellt. So, und nun geht es weiter natürlich mit Musik.',
      sentenceTranslations: {
        'Hier ist Radio München, guten Morgen allerseits.': { literal: 'Здесь есть Радио Мюнхен, доброе утро всем', literary: 'Это Радио Мюнхен, всем доброе утро.' },
        'Nach diesem fantastischen Wochenende wünsche ich euch allen einen wunderschönen Montagmorgen.': { literal: 'После этих фантастических выходных желаю я вам всем прекрасное утро понедельника', literary: 'После фантастических выходных желаю всем вам прекрасного утра понедельника.' },
        'Wir hatten am Samstag und Sonntag volles Programm.': { literal: 'Мы имели в субботу и воскресенье полную программу', literary: 'У нас была насыщенная программа в субботу и воскресенье.' },
        'Konzerte, Theatervorstellungen und viele interessante Filme in den Kinos.': { literal: 'Концерты, театральные представления и много интересных фильмов в кинотеатрах', literary: 'Концерты, театральные представления и много интересных фильмов в кинотеатрах.' },
        'Außerdem haben wir im Rock-Club verschiedene neue Bands vorgestellt.': { literal: 'Кроме того имеем мы в рок-клубе различные новые группы представили', literary: 'Кроме того, мы представили в рок-клубе различные новые группы.' },
        'So, und nun geht es weiter natürlich mit Musik.': { literal: 'Так, и теперь идёт это дальше конечно с музыкой', literary: 'Итак, продолжаем, конечно же, с музыкой.' },
      },
      vocabulary: [
        { de: 'das Wochenende', plural: 'die Wochenenden', ru: 'выходные', gender: 'neutrum', collocation: 'fantastisches Wochenende', example: 'Nach diesem fantastischen Wochenende.' },
        { de: 'der Montagmorgen', plural: 'die Montagmorgen', ru: 'утро понедельника', gender: 'maskulin', collocation: 'wunderschöner Montagmorgen', example: 'Wünsche ich euch allen einen wunderschönen Montagmorgen.' },
        { de: 'das Programm', plural: 'die Programme', ru: 'программа', gender: 'neutrum', collocation: 'volles Programm', example: 'Wir hatten am Samstag und Sonntag volles Programm.' },
        { de: 'das Konzert', plural: 'die Konzerte', ru: 'концерт', gender: 'neutrum', collocation: 'Konzerte am Wochenende', example: 'Konzerte, Theatervorstellungen und viele interessante Filme.' },
        { de: 'die Theatervorstellung', plural: 'die Theatervorstellungen', ru: 'театральное представление', gender: 'feminin', collocation: 'interessante Theatervorstellungen', example: 'Konzerte, Theatervorstellungen und viele interessante Filme in den Kinos.' },
        { de: 'die Band', plural: 'die Bands', ru: 'музыкальная группа', gender: 'feminin', collocation: 'neue Bands vorstellen', example: 'Außerdem haben wir im Rock-Club verschiedene neue Bands vorgestellt.' },
        { de: 'wünschen', ru: 'желать', type: 'verb', forms: 'wünscht, wünschte, hat gewünscht', example: 'Wünsche ich euch allen einen wunderschönen Montagmorgen.' },
        { de: 'vorstellen', ru: 'представлять', type: 'verb', forms: 'stellt vor, stellte vor, hat vorgestellt', example: 'Außerdem haben wir im Rock-Club verschiedene neue Bands vorgestellt.' },
        { de: 'fantastisch', ru: 'фантастический', type: 'adj', example: 'Nach diesem fantastischen Wochenende.' },
        { de: 'verschieden', ru: 'различный', type: 'adj', example: 'Außerdem haben wir im Rock-Club verschiedene neue Bands vorgestellt.' },
      ],
      practiceSentences: [
        { de: 'Am Wochenende hatte ich viel Spaß.', ru: 'На выходных мне было весело.', note: 'hatte на V2' },
        { de: 'Wir haben gestern Musik gehört.', ru: 'Мы вчера слушали музыку.', note: 'Perfekt: haben...gehört' },
        { de: 'Das Radio spielt neue Lieder.', ru: 'Радио играет новые песни.', note: 'spielt на V2' },
        { de: 'Er stellt seine Freunde vor.', ru: 'Он представляет своих друзей.', note: 'отделяемая приставка vor-' },
        { de: 'Nun geht das Konzert weiter.', ru: 'Теперь концерт продолжается.', note: 'geht на V2' },
      ],
      question: {
        de: 'Was gab es am Wochenende?',
        ru: 'Что было на выходных?',
        options: [
          { de: 'Nur Konzerte', ru: 'Только концерты' },
          { de: 'Volles Programm mit verschiedenen Veranstaltungen', ru: 'Насыщенная программа с различными мероприятиями' },
          { de: 'Nur neue Bands im Rock-Club', ru: 'Только новые группы в рок-клубе' },
        ],
        correct: 1,
        explanation: 'В тексте сказано: "wir hatten am Samstag und Sonntag volles Programm: Konzerte, Theatervorstellungen und viele interessante Filme".'
      }
    },
    {
      id: 'text-3', teil: 1, aufgabe: 3,
      name: 'Rechnung',
      type: 'диалог в магазине',
      text: 'So, haben wir jetzt alles? Dann mache ich die Rechnung. Der Bleistift kostet 80, falsch, 90 Cent. Der Kugelschreiber kostet 2,90 Euro. Und die vier Farbstifte kosten das Stück 80 Cent, insgesamt also 3,20 Euro. Was hast du noch? Zwei Radiergummis, das Stück ein Euro 10, macht 2,20 Euro. Und das Notizbuch 5,50 Euro. Das macht zusammen 14,70.',
      sentenceTranslations: {
        'So, haben wir jetzt alles?': { literal: 'Так, имеем мы сейчас всё?', literary: 'Так, у нас всё есть?' },
        'Dann mache ich die Rechnung.': { literal: 'Тогда делаю я счёт', literary: 'Тогда я посчитаю.' },
        'Der Bleistift kostet 80, falsch, 90 Cent.': { literal: 'Карандаш стоит 80, неправильно, 90 центов', literary: 'Карандаш стоит 80, нет, 90 центов.' },
        'Der Kugelschreiber kostet 2,90 Euro.': { literal: 'Шариковая ручка стоит 2,90 евро', literary: 'Ручка стоит 2,90 евро.' },
        'Und die vier Farbstifte kosten das Stück 80 Cent, insgesamt also 3,20 Euro.': { literal: 'И четыре цветных карандаша стоят штука 80 центов, всего итак 3,20 евро', literary: 'Четыре цветных карандаша по 80 центов за штуку, итого 3,20 евро.' },
        'Was hast du noch?': { literal: 'Что имеешь ты ещё?', literary: 'Что у тебя ещё?' },
        'Zwei Radiergummis, das Stück ein Euro 10, macht 2,20 Euro.': { literal: 'Два ластика, штука один евро 10, делает 2,20 евро', literary: 'Два ластика по 1,10 евро, получается 2,20 евро.' },
        'Und das Notizbuch 5,50 Euro.': { literal: 'И блокнот 5,50 евро', literary: 'И блокнот 5,50 евро.' },
        'Das macht zusammen 14,70.': { literal: 'Это делает вместе 14,70', literary: 'Всего получается 14,70.' },
      },
      vocabulary: [
        { de: 'die Rechnung', plural: 'die Rechnungen', ru: 'счёт', gender: 'feminin', collocation: 'die Rechnung machen', example: 'Dann mache ich die Rechnung.' },
        { de: 'der Bleistift', plural: 'die Bleistifte', ru: 'карандаш', gender: 'maskulin', collocation: 'der Bleistift kostet', example: 'Der Bleistift kostet 80, falsch, 90 Cent.' },
        { de: 'der Kugelschreiber', plural: 'die Kugelschreiber', ru: 'шариковая ручка', gender: 'maskulin', collocation: 'Kugelschreiber kaufen', example: 'Der Kugelschreiber kostet 2,90 Euro.' },
        { de: 'der Farbstift', plural: 'die Farbstifte', ru: 'цветной карандаш', gender: 'maskulin', collocation: 'vier Farbstifte', example: 'Und die vier Farbstifte kosten das Stück 80 Cent.' },
        { de: 'das Radiergummi', plural: 'die Radiergummis', ru: 'ластик', gender: 'neutrum', collocation: 'zwei Radiergummis', example: 'Zwei Radiergummis, das Stück ein Euro 10.' },
        { de: 'das Notizbuch', plural: 'die Notizbücher', ru: 'блокнот', gender: 'neutrum', collocation: 'das Notizbuch kostet', example: 'Und das Notizbuch 5,50 Euro.' },
        { de: 'das Stück', plural: 'die Stücke', ru: 'штука', gender: 'neutrum', collocation: 'das Stück 80 Cent', example: 'Die vier Farbstifte kosten das Stück 80 Cent.' },
        { de: 'kosten', ru: 'стоить', type: 'verb', forms: 'kostet, kostete, hat gekostet', example: 'Der Bleistift kostet 80, falsch, 90 Cent.' },
        { de: 'insgesamt', ru: 'всего, итого', type: 'adv', example: 'Und die vier Farbstifte kosten das Stück 80 Cent, insgesamt also 3,20 Euro.' },
        { de: 'zusammen', ru: 'вместе, всего', type: 'adv', example: 'Das macht zusammen 14,70.' },
      ],
      practiceSentences: [
        { de: 'Das Buch kostet zehn Euro.', ru: 'Книга стоит десять евро.', note: 'kostet на V2' },
        { de: 'Was macht das zusammen?', ru: 'Сколько всего получается?', note: 'macht на V2' },
        { de: 'Die Äpfel kosten das Kilo zwei Euro.', ru: 'Яблоки стоят два евро за килограмм.', note: 'kosten на V2' },
        { de: 'Ich mache schnell die Rechnung.', ru: 'Я быстро посчитаю.', note: 'mache на V2' },
        { de: 'Hast du noch etwas?', ru: 'У тебя ещё что-нибудь есть?', note: 'V1 в вопросе' },
      ],
      question: {
        de: 'Wie viel kostet alles zusammen?',
        ru: 'Сколько стоит всё вместе?',
        options: [
          { de: '12,50 Euro', ru: '12,50 евро' },
          { de: '14,70 Euro', ru: '14,70 евро' },
          { de: '15,20 Euro', ru: '15,20 евро' },
        ],
        correct: 1,
        explanation: 'В конце подсчёта говорится: "das macht zusammen 14,70" — общая сумма составляет 14,70 евро.'
      }
    },
    {
      id: 'text-4', teil: 1, aufgabe: 4,
      name: 'Mama',
      type: 'голосовое сообщение',
      text: 'Hallo Markus, hier spricht Mama. Leider muss ich heute länger im Büro bleiben. Ich habe wichtige Arbeit, die erledigt werden muss. Bitte hol deinen Bruder um 17 Uhr 30 vom Fußballtraining ab. Du weißt doch, Andreas hat Angst alleine nach Hause zu kommen. Und ich kann niemanden von den anderen Eltern erreichen. Vati kommt gegen 18 Uhr von der Arbeit und ich bin spätestens um 18:30 Uhr auch zu Hause. Bis dann.',
      sentenceTranslations: {
        'Hallo Markus, hier spricht Mama.': { literal: 'Привет Маркус, здесь говорит мама', literary: 'Привет, Маркус, это мама.' },
        'Leider muss ich heute länger im Büro bleiben.': { literal: 'К сожалению должна я сегодня дольше в офисе остаться', literary: 'К сожалению, я должна сегодня задержаться в офисе.' },
        'Ich habe wichtige Arbeit, die erledigt werden muss.': { literal: 'Я имею важную работу, которая выполнена быть должна', literary: 'У меня важная работа, которую нужно закончить.' },
        'Bitte hol deinen Bruder um 17 Uhr 30 vom Fußballtraining ab.': { literal: 'Пожалуйста забери твоего брата в 17:30 с футбольной тренировки', literary: 'Пожалуйста, забери брата в 17:30 с футбольной тренировки.' },
        'Du weißt doch, Andreas hat Angst alleine nach Hause zu kommen.': { literal: 'Ты знаешь же, Андреас имеет страх один домой прийти', literary: 'Ты же знаешь, Андреас боится идти домой один.' },
        'Und ich kann niemanden von den anderen Eltern erreichen.': { literal: 'И я могу никого из других родителей достичь', literary: 'И я не могу дозвониться другим родителям.' },
        'Vati kommt gegen 18 Uhr von der Arbeit und ich bin spätestens um 18:30 Uhr auch zu Hause.': { literal: 'Папа приходит около 18 часов с работы и я есть самое позднее в 18:30 тоже дома', literary: 'Папа придёт с работы около 18:00, и я буду дома самое позднее в 18:30.' },
        'Bis dann.': { literal: 'До тогда', literary: 'До встречи.' },
      },
      vocabulary: [
        { de: 'das Büro', plural: 'die Büros', ru: 'офис', gender: 'neutrum', collocation: 'länger im Büro bleiben', example: 'Leider muss ich heute länger im Büro bleiben.' },
        { de: 'die Arbeit', plural: 'die Arbeiten', ru: 'работа', gender: 'feminin', collocation: 'wichtige Arbeit', example: 'Ich habe wichtige Arbeit, die erledigt werden muss.' },
        { de: 'der Bruder', plural: 'die Brüder', ru: 'брат', gender: 'maskulin', collocation: 'deinen Bruder abholen', example: 'Bitte hol deinen Bruder um 17 Uhr 30 vom Fußballtraining ab.' },
        { de: 'das Fußballtraining', plural: 'die Fußballtrainings', ru: 'футбольная тренировка', gender: 'neutrum', collocation: 'vom Fußballtraining abholen', example: 'Bitte hol deinen Bruder um 17 Uhr 30 vom Fußballtraining ab.' },
        { de: 'die Angst', plural: 'die Ängste', ru: 'страх', gender: 'feminin', collocation: 'Angst haben', example: 'Andreas hat Angst alleine nach Hause zu kommen.' },
        { de: 'die Eltern', ru: 'родители (только мн.ч.)', gender: 'plural', collocation: 'von den anderen Eltern', example: 'Und ich kann niemanden von den anderen Eltern erreichen.' },
        { de: 'abholen', ru: 'забирать', type: 'verb', forms: 'holt ab, holte ab, hat abgeholt', example: 'Bitte hol deinen Bruder um 17 Uhr 30 vom Fußballtraining ab.' },
        { de: 'erledigen', ru: 'выполнять, заканчивать', type: 'verb', forms: 'erledigt, erledigte, hat erledigt', example: 'Ich habe wichtige Arbeit, die erledigt werden muss.' },
        { de: 'erreichen', ru: 'дозвониться, достичь', type: 'verb', forms: 'erreicht, erreichte, hat erreicht', example: 'Und ich kann niemanden von den anderen Eltern erreichen.' },
        { de: 'spätestens', ru: 'самое позднее', type: 'adv', example: 'Ich bin spätestens um 18:30 Uhr auch zu Hause.' },
      ],
      practiceSentences: [
        { de: 'Ich muss heute länger arbeiten.', ru: 'Я должен сегодня дольше работать.', note: 'muss + инфинитив' },
        { de: 'Hol mich bitte ab!', ru: 'Забери меня, пожалуйста!', note: 'императив с отделяемой приставкой' },
        { de: 'Die Arbeit muss gemacht werden.', ru: 'Работа должна быть сделана.', note: 'пассив с модальным' },
        { de: 'Er hat Angst zu fahren.', ru: 'Он боится ехать.', note: 'конструкция с zu + Infinitiv' },
        { de: 'Papa kommt gegen sieben Uhr.', ru: 'Папа придёт около семи.', note: 'kommt на V2' },
      ],
      question: {
        de: 'Um wie viel Uhr muss Markus seinen Bruder abholen?',
        ru: 'Во сколько Маркус должен забрать брата?',
        options: [
          { de: 'Um 17:00 Uhr', ru: 'В 17:00' },
          { de: 'Um 17:30 Uhr', ru: 'В 17:30' },
          { de: 'Um 18:00 Uhr', ru: 'В 18:00' },
        ],
        correct: 1,
        explanation: 'Мама говорит: "bitte hol deinen Bruder um 17 Uhr 30 vom Fußballtraining ab" — забрать брата нужно в 17:30.'
      }
    },
    {
      id: 'text-5', teil: 1, aufgabe: 5,
      name: 'Verkehr/Wetter',
      type: 'объявления',
      text: 'Achtung Autofahrer, wegen dringender Reparaturarbeiten bleibt die Rheinstraße zwischen Goethe- und Schillerstraße bis übermorgen gesperrt. Und nun die Wettervorhersage für morgen: nur im Norden Regen bei 15 Grad, sonst meist sonnig und warm. Im Süden sehr warm mit Tageshöchsttemperaturen um 28 Grad.',
      sentenceTranslations: {
        'Achtung Autofahrer, wegen dringender Reparaturarbeiten bleibt die Rheinstraße zwischen Goethe- und Schillerstraße bis übermorgen gesperrt.': { literal: 'Внимание автоводители, из-за срочных ремонтных работ остаётся Рейнштрассе между Гёте- и Шиллерштрассе до послезавтра закрытой', literary: 'Внимание, автомобилисты: из-за срочных ремонтных работ Рейнштрассе между улицами Гёте и Шиллера закрыта до послезавтра.' },
        'Und nun die Wettervorhersage für morgen: nur im Norden Regen bei 15 Grad, sonst meist sonnig und warm.': { literal: 'И теперь прогноз погоды на завтра: только на севере дождь при 15 градусах, иначе преимущественно солнечно и тепло', literary: 'А теперь прогноз погоды на завтра: только на севере дождь при 15 градусах, в остальных регионах преимущественно солнечно и тепло.' },
        'Im Süden sehr warm mit Tageshöchsttemperaturen um 28 Grad.': { literal: 'На юге очень тепло с дневными максимальными температурами около 28 градусов', literary: 'На юге очень тепло, максимальная температура около 28 градусов.' },
      },
      vocabulary: [
        { de: 'der Autofahrer', plural: 'die Autofahrer', ru: 'водитель', gender: 'maskulin', collocation: 'Achtung Autofahrer', example: 'Achtung Autofahrer, wegen dringender Reparaturarbeiten.' },
        { de: 'die Straße', plural: 'die Straßen', ru: 'улица', gender: 'feminin', collocation: 'die Rheinstraße', example: 'Die Rheinstraße zwischen Goethe- und Schillerstraße bleibt gesperrt.' },
        { de: 'die Wettervorhersage', plural: 'die Wettervorhersagen', ru: 'прогноз погоды', gender: 'feminin', collocation: 'Wettervorhersage für morgen', example: 'Und nun die Wettervorhersage für morgen.' },
        { de: 'der Norden', ru: 'север', gender: 'maskulin', collocation: 'im Norden', example: 'Nur im Norden Regen bei 15 Grad.' },
        { de: 'der Süden', ru: 'юг', gender: 'maskulin', collocation: 'im Süden', example: 'Im Süden sehr warm mit Tageshöchsttemperaturen um 28 Grad.' },
        { de: 'der Grad', plural: 'die Grade', ru: 'градус', gender: 'maskulin', collocation: 'bei 15 Grad', example: 'Nur im Norden Regen bei 15 Grad.' },
        { de: 'gesperrt', ru: 'закрытый, перекрытый', type: 'adj', example: 'Die Rheinstraße bleibt bis übermorgen gesperrt.' },
        { de: 'dringend', ru: 'срочный', type: 'adj', example: 'Wegen dringender Reparaturarbeiten.' },
        { de: 'sonnig', ru: 'солнечный', type: 'adj', example: 'Sonst meist sonnig und warm.' },
      ],
      practiceSentences: [
        { de: 'Die Straße bleibt gesperrt.', ru: 'Улица остаётся закрытой.', note: 'bleibt на V2' },
        { de: 'Wegen Regen bleiben wir zu Hause.', ru: 'Из-за дождя мы остаёмся дома.', note: 'bleiben на V2 после обстоятельства' },
        { de: 'Morgen wird es warm.', ru: 'Завтра будет тепло.', note: 'wird на V2' },
        { de: 'Es regnet nur im Norden.', ru: 'Дождь идёт только на севере.', note: 'безличное es' },
        { de: 'Die Temperatur liegt bei 20 Grad.', ru: 'Температура составляет 20 градусов.', note: 'liegt на V2' },
      ],
      question: {
        de: 'Wie ist das Wetter morgen im Süden?',
        ru: 'Какая погода завтра на юге?',
        options: [
          { de: 'Regen bei 15 Grad', ru: 'Дождь при 15 градусах' },
          { de: 'Sonnig bei 20 Grad', ru: 'Солнечно при 20 градусах' },
          { de: 'Sehr warm mit 28 Grad', ru: 'Очень тепло, 28 градусов' },
        ],
        correct: 2,
        explanation: 'В прогнозе сказано: "im Süden sehr warm mit Tageshöchsttemperaturen um 28 Grad" — на юге очень тепло, около 28 градусов.'
      }
    },

    /* ═══ TEIL 2 — 1 длинный диалог ═══ */
    {
      id: 'text-6', teil: 2, aufgabe: 6,
      name: 'Carmens Geburtstag',
      type: 'диалог',
      text: 'Carmen Schmidt, hallo Carmen, nachträglich alles Gute zum Geburtstag. Tut mir leid, dass ich nicht zu deiner Geburtstagsparty kommen konnte. Ich hatte nämlich hohes Fieber. Mir geht es heute auch nicht so gut, ich trinke gerade eine Tasse Tee. Mein Hals tut weh. Geht es dir jetzt besser? Ja, zum Glück. Erzähl mal, wie war denn die Party? Die Party war super. Paul hat tolle Musik mitgebracht, auch von unserer Lieblingsband. Ist Luise auch gekommen? Ja, und sie hat die ganze Nacht mit allen Jungs getanzt. Und Nadine hatte eine tolle Überraschung für mich, sie hat eine Torte für mich gemacht, echt lecker. Natürlich gab es jede Menge Erfrischungsgetränke: Fanta, Cola, Sprite. Was hast du noch bekommen? Von meinen Eltern habe ich ein cooles Rad bekommen. Du hast es aber gut. Vielleicht treffen wir uns die nächsten Tage, ich möchte dir nämlich auch mein Geschenk geben. Okay, komm doch morgen Nachmittag zu mir. Abgemacht, bis morgen dann.',
      sentenceTranslations: {
        'Carmen Schmidt, hallo Carmen, nachträglich alles Gute zum Geburtstag.': { literal: 'Кармен Шмидт, привет Кармен, запоздало всё хорошее к дню рождения', literary: 'Кармен Шмидт, привет, Кармен, с прошедшим днём рождения.' },
        'Tut mir leid, dass ich nicht zu deiner Geburtstagsparty kommen konnte.': { literal: 'Делает мне жаль, что я не на твою вечеринку прийти мог', literary: 'Извини, что не смог прийти на твою вечеринку.' },
        'Ich hatte nämlich hohes Fieber.': { literal: 'Я имел именно высокую температуру', literary: 'У меня была высокая температура.' },
        'Mir geht es heute auch nicht so gut, ich trinke gerade eine Tasse Tee.': { literal: 'Мне идёт это сегодня тоже не так хорошо, я пью как раз чашку чая', literary: 'Мне и сегодня не очень хорошо, я как раз пью чашку чая.' },
        'Mein Hals tut weh.': { literal: 'Моё горло делает больно', literary: 'У меня болит горло.' },
        'Geht es dir jetzt besser?': { literal: 'Идёт оно тебе сейчас лучше?', literary: 'Тебе уже лучше?' },
        'Ja, zum Glück.': { literal: 'Да, к счастью', literary: 'Да, к счастью.' },
        'Erzähl mal, wie war denn die Party?': { literal: 'Расскажи-ка, как была же вечеринка?', literary: 'Расскажи, как прошла вечеринка?' },
        'Die Party war super.': { literal: 'Вечеринка была супер', literary: 'Вечеринка была отличной.' },
        'Paul hat tolle Musik mitgebracht, auch von unserer Lieblingsband.': { literal: 'Пауль имеет классную музыку принёс, также от нашей любимой группы', literary: 'Пауль принёс классную музыку, в том числе нашей любимой группы.' },
        'Ist Luise auch gekommen?': { literal: 'Есть Луизе тоже пришла?', literary: 'Луиза тоже пришла?' },
        'Ja, und sie hat die ganze Nacht mit allen Jungs getanzt.': { literal: 'Да, и она имеет всю ночь со всеми парнями танцевала', literary: 'Да, и она всю ночь танцевала со всеми парнями.' },
        'Und Nadine hatte eine tolle Überraschung für mich, sie hat eine Torte für mich gemacht, echt lecker.': { literal: 'И Надин имела классный сюрприз для меня, она имеет торт для меня сделала, действительно вкусно', literary: 'У Надин был для меня классный сюрприз — она сделала мне торт, очень вкусный.' },
        'Natürlich gab es jede Menge Erfrischungsgetränke: Fanta, Cola, Sprite.': { literal: 'Конечно давало оно каждое количество прохладительных напитков', literary: 'Конечно, было полно прохладительных напитков: Фанта, Кола, Спрайт.' },
        'Was hast du noch bekommen?': { literal: 'Что имеешь ты ещё получил?', literary: 'Что ты ещё получила?' },
        'Von meinen Eltern habe ich ein cooles Rad bekommen.': { literal: 'От моих родителей имею я классный велосипед получил', literary: 'От родителей я получила классный велосипед.' },
        'Du hast es aber gut.': { literal: 'Ты имеешь это но хорошо', literary: 'Везёт тебе.' },
        'Vielleicht treffen wir uns die nächsten Tage, ich möchte dir nämlich auch mein Geschenk geben.': { literal: 'Возможно встречаем мы себя следующие дни, я хотел бы тебе именно тоже мой подарок дать', literary: 'Может, встретимся на днях — я тоже хочу подарить тебе подарок.' },
        'Okay, komm doch morgen Nachmittag zu mir.': { literal: 'Хорошо, приходи же завтра послеобеденное-время ко мне', literary: 'Хорошо, приходи завтра днём ко мне.' },
        'Abgemacht, bis morgen dann.': { literal: 'Договорено, до завтра тогда', literary: 'Договорились, до завтра.' },
      },
      vocabulary: [
        { de: 'der Geburtstag', plural: 'die Geburtstage', ru: 'день рождения', gender: 'maskulin', collocation: 'alles Gute zum Geburtstag', example: 'Nachträglich alles Gute zum Geburtstag.' },
        { de: 'die Geburtstagsparty', plural: 'die Geburtstagspartys', ru: 'вечеринка в честь дня рождения', gender: 'feminin', collocation: 'zu deiner Geburtstagsparty', example: 'Tut mir leid, dass ich nicht zu deiner Geburtstagsparty kommen konnte.' },
        { de: 'das Fieber', ru: 'температура, жар', gender: 'neutrum', collocation: 'hohes Fieber haben', example: 'Ich hatte nämlich hohes Fieber.' },
        { de: 'die Tasse', plural: 'die Tassen', ru: 'чашка', gender: 'feminin', collocation: 'eine Tasse Tee', example: 'Ich trinke gerade eine Tasse Tee.' },
        { de: 'der Hals', plural: 'die Hälse', ru: 'горло', gender: 'maskulin', collocation: 'der Hals tut weh', example: 'Mein Hals tut weh.' },
        { de: 'die Überraschung', plural: 'die Überraschungen', ru: 'сюрприз', gender: 'feminin', collocation: 'eine tolle Überraschung', example: 'Und Nadine hatte eine tolle Überraschung für mich.' },
        { de: 'die Torte', plural: 'die Torten', ru: 'торт', gender: 'feminin', collocation: 'eine Torte machen', example: 'Sie hat eine Torte für mich gemacht.' },
        { de: 'das Rad', plural: 'die Räder', ru: 'велосипед', gender: 'neutrum', collocation: 'ein cooles Rad', example: 'Von meinen Eltern habe ich ein cooles Rad bekommen.' },
        { de: 'das Geschenk', plural: 'die Geschenke', ru: 'подарок', gender: 'neutrum', collocation: 'mein Geschenk geben', example: 'Ich möchte dir nämlich auch mein Geschenk geben.' },
        { de: 'mitbringen', ru: 'приносить с собой', type: 'verb', forms: 'bringt mit, brachte mit, hat mitgebracht', example: 'Paul hat tolle Musik mitgebracht.' },
        { de: 'tanzen', ru: 'танцевать', type: 'verb', forms: 'tanzt, tanzte, hat getanzt', example: 'Sie hat die ganze Nacht mit allen Jungs getanzt.' },
        { de: 'bekommen', ru: 'получать', type: 'verb', forms: 'bekommt, bekam, hat bekommen', example: 'Von meinen Eltern habe ich ein cooles Rad bekommen.' },
        { de: 'nachträglich', ru: 'с опозданием', type: 'adv', example: 'Nachträglich alles Gute zum Geburtstag.' },
        { de: 'lecker', ru: 'вкусный', type: 'adj', example: 'Sie hat eine Torte für mich gemacht, echt lecker.' },
      ],
      practiceSentences: [
        { de: 'Es tut mir sehr leid.', ru: 'Мне очень жаль.', note: 'безличный глагол tut на V2' },
        { de: 'Gestern hatte ich Fieber.', ru: 'Вчера у меня была температура.', note: 'hatte на V2' },
        { de: 'Sie hat Kuchen mitgebracht.', ru: 'Она принесла пирог.', note: 'Perfekt с отделяемой приставкой' },
        { de: 'Mir geht es heute besser.', ru: 'Мне сегодня лучше.', note: 'geht на V2, безличная конструкция' },
        { de: 'Der Kopf tut mir weh.', ru: 'У меня болит голова.', note: 'tut на V2' },
      ],
      question: {
        de: 'Warum konnte die Person nicht zur Party kommen?',
        ru: 'Почему человек не смог прийти на вечеринку?',
        options: [
          { de: 'Sie hatte keine Zeit', ru: 'Не было времени' },
          { de: 'Sie hatte hohes Fieber', ru: 'Была высокая температура' },
          { de: 'Sie war im Urlaub', ru: 'Был(а) в отпуске' },
        ],
        correct: 1,
        explanation: 'Говорящий объясняет: "ich hatte nämlich hohes Fieber" — у него была высокая температура.'
      }
    },

    /* ═══ TEIL 3 — 5 коротких диалогов ═══ */
    {
      id: 'text-7', teil: 3, aufgabe: 11,
      name: 'Abendessen',
      type: 'диалог за столом',
      text: 'Komm, Schatz, das Essen ist fertig. Was gibt es? Schnitzel mit Pommes und Salat. Und natürlich gibt es nach dem Essen auch Eis. Toll, am liebsten würde ich zuerst das Eis essen. Du weißt, dass das nicht richtig ist. Iss jetzt dein Schnitzel. Ich esse erstmal Salat, der sieht echt lecker aus.',
      sentenceTranslations: {
        'Komm, Schatz, das Essen ist fertig.': { literal: 'Приходи, сокровище, еда есть готовая', literary: 'Иди, дорогой, ужин готов.' },
        'Was gibt es?': { literal: 'Что даётся?', literary: 'Что на ужин?' },
        'Schnitzel mit Pommes und Salat.': { literal: 'Шницель с картофелем фри и салатом', literary: 'Шницель с картошкой фри и салатом.' },
        'Und natürlich gibt es nach dem Essen auch Eis.': { literal: 'И конечно даётся после еды также мороженое', literary: 'И конечно, после ужина будет мороженое.' },
        'Toll, am liebsten würde ich zuerst das Eis essen.': { literal: 'Классно, охотнее всего бы я сначала мороженое съел', literary: 'Здорово, я бы лучше сначала съел мороженое.' },
        'Du weißt, dass das nicht richtig ist.': { literal: 'Ты знаешь, что это не правильно есть', literary: 'Ты знаешь, что так нельзя.' },
        'Iss jetzt dein Schnitzel.': { literal: 'Ешь сейчас твой шницель', literary: 'Ешь свой шницель.' },
        'Ich esse erstmal Salat, der sieht echt lecker aus.': { literal: 'Я ем сначала салат, он выглядит действительно вкусно', literary: 'Я сначала съем салат, он выглядит очень аппетитно.' },
      },
      vocabulary: [
        { de: 'das Essen', plural: 'die Essen', ru: 'еда, ужин', gender: 'neutrum', collocation: 'das Essen ist fertig', example: 'Komm, Schatz, das Essen ist fertig.' },
        { de: 'das Schnitzel', plural: 'die Schnitzel', ru: 'шницель', gender: 'neutrum', collocation: 'Schnitzel mit Pommes', example: 'Schnitzel mit Pommes und Salat.' },
        { de: 'der Salat', plural: 'die Salate', ru: 'салат', gender: 'maskulin', collocation: 'Salat essen', example: 'Ich esse erstmal Salat, der sieht echt lecker aus.' },
        { de: 'das Eis', ru: 'мороженое', gender: 'neutrum', collocation: 'nach dem Essen Eis', example: 'Und natürlich gibt es nach dem Essen auch Eis.' },
        { de: 'aussehen', ru: 'выглядеть', type: 'verb', forms: 'sieht aus, sah aus, hat ausgesehen', example: 'Ich esse erstmal Salat, der sieht echt lecker aus.' },
        { de: 'fertig', ru: 'готовый', type: 'adj', example: 'Komm, Schatz, das Essen ist fertig.' },
        { de: 'lecker', ru: 'вкусный, аппетитный', type: 'adj', example: 'Ich esse erstmal Salat, der sieht echt lecker aus.' },
      ],
      practiceSentences: [
        { de: 'Das Essen ist fertig.', ru: 'Еда готова.', note: 'ist на V2' },
        { de: 'Was gibt es heute?', ru: 'Что сегодня на обед?', note: 'безличная конструкция es gibt' },
        { de: 'Ich würde gern Pizza essen.', ru: 'Я бы с удовольствием поел пиццу.', note: 'Konjunktiv II würde' },
        { de: 'Iss dein Gemüse!', ru: 'Ешь свои овощи!', note: 'императив от essen' },
        { de: 'Das sieht lecker aus.', ru: 'Это выглядит вкусно.', note: 'отделяемая приставка aussehen' },
      ],
      question: {
        de: 'Was möchte das Kind zuerst essen?',
        ru: 'Что ребёнок хочет съесть сначала?',
        options: [
          { de: 'Schnitzel', ru: 'Шницель' },
          { de: 'Salat', ru: 'Салат' },
          { de: 'Eis', ru: 'Мороженое' },
        ],
        correct: 2,
        explanation: 'Ребёнок говорит: "am liebsten würde ich zuerst das Eis essen" — больше всего хотел бы сначала съесть мороженое.'
      }
    },
    {
      id: 'text-8', teil: 3, aufgabe: 12,
      name: 'Geschenk für Marie',
      type: 'диалог о подарке',
      text: 'Du, Bianca, Marie hat doch am Samstag Geburtstag. Kaufen wir ihr ein Geschenk zusammen? Ja, warum nicht. Vielleicht eine Tasche. Maria hat viele Taschen. Oder lieber eine Halskette, was meinst du? Ich weiß nicht, noch eine Tasche, noch eine Halskette. Schau, hier dieses Buch gefällt ihr bestimmt: schnelles und einfaches Kochen. Ein Kochbuch? Ja, Kochen ist doch ihr Hobby. Okay, wenn es so ist, dann kaufen wir das Kochbuch.',
      sentenceTranslations: {
        'Du, Bianca, Marie hat doch am Samstag Geburtstag.': { literal: 'Ты, Бьянка, Мари имеет же в субботу день рождения', literary: 'Слушай, Бьянка, у Мари же в субботу день рождения.' },
        'Kaufen wir ihr ein Geschenk zusammen?': { literal: 'Купим мы ей подарок вместе?', literary: 'Купим ей подарок вместе?' },
        'Ja, warum nicht.': { literal: 'Да, почему нет', literary: 'Да, почему бы и нет.' },
        'Vielleicht eine Tasche.': { literal: 'Возможно сумку', literary: 'Может, сумку.' },
        'Maria hat viele Taschen.': { literal: 'Мария имеет много сумок', literary: 'У Марии много сумок.' },
        'Oder lieber eine Halskette, was meinst du?': { literal: 'Или лучше ожерелье, что думаешь ты?', literary: 'Или лучше ожерелье, что думаешь?' },
        'Ich weiß nicht, noch eine Tasche, noch eine Halskette.': { literal: 'Я знаю не, ещё одну сумку, ещё одно ожерелье', literary: 'Не знаю, ни сумку, ни ожерелье.' },
        'Schau, hier dieses Buch gefällt ihr bestimmt: schnelles und einfaches Kochen.': { literal: 'Смотри, здесь эта книга нравится ей точно: быстрое и простое приготовление', literary: 'Смотри, вот эта книга ей точно понравится: быстрая и простая готовка.' },
        'Ein Kochbuch?': { literal: 'Поваренная книга?', literary: 'Кулинарная книга?' },
        'Ja, Kochen ist doch ihr Hobby.': { literal: 'Да, готовка есть же её хобби', literary: 'Да, готовка же её хобби.' },
        'Okay, wenn es so ist, dann kaufen wir das Kochbuch.': { literal: 'Хорошо, если это так есть, тогда покупаем мы поваренную книгу', literary: 'Хорошо, раз так, купим кулинарную книгу.' },
      },
      vocabulary: [
        { de: 'die Tasche', plural: 'die Taschen', ru: 'сумка', gender: 'feminin', collocation: 'viele Taschen haben', example: 'Maria hat viele Taschen.' },
        { de: 'die Halskette', plural: 'die Halsketten', ru: 'ожерелье', gender: 'feminin', collocation: 'eine Halskette schenken', example: 'Oder lieber eine Halskette, was meinst du?' },
        { de: 'das Kochbuch', plural: 'die Kochbücher', ru: 'кулинарная книга', gender: 'neutrum', collocation: 'das Kochbuch kaufen', example: 'Okay, wenn es so ist, dann kaufen wir das Kochbuch.' },
        { de: 'das Hobby', plural: 'die Hobbys', ru: 'хобби', gender: 'neutrum', collocation: 'Kochen ist ihr Hobby', example: 'Ja, Kochen ist doch ihr Hobby.' },
        { de: 'gefallen', ru: 'нравиться', type: 'verb', forms: 'gefällt, gefiel, hat gefallen', example: 'Schau, hier dieses Buch gefällt ihr bestimmt.' },
        { de: 'meinen', ru: 'думать, считать', type: 'verb', forms: 'meint, meinte, hat gemeint', example: 'Oder lieber eine Halskette, was meinst du?' },
        { de: 'bestimmt', ru: 'точно, наверняка', type: 'adv', example: 'Schau, hier dieses Buch gefällt ihr bestimmt.' },
        { de: 'einfach', ru: 'простой', type: 'adj', example: 'Schau, hier dieses Buch gefällt ihr bestimmt: schnelles und einfaches Kochen.' },
      ],
      practiceSentences: [
        { de: 'Sie hat am Montag Geburtstag.', ru: 'У неё в понедельник день рождения.', note: 'hat на V2' },
        { de: 'Kaufen wir etwas zusammen?', ru: 'Купим что-нибудь вместе?', note: 'V1 в вопросе' },
        { de: 'Das Buch gefällt mir.', ru: 'Мне нравится эта книга.', note: 'gefällt на V2 с Dativ' },
        { de: 'Wenn du willst, dann gehen wir.', ru: 'Если хочешь, пойдём.', note: 'глагол в конце wenn-Satz' },
        { de: 'Kochen ist mein Hobby.', ru: 'Готовка — моё хобби.', note: 'ist на V2' },
      ],
      question: {
        de: 'Was kaufen sie für Marie?',
        ru: 'Что они покупают для Мари?',
        options: [
          { de: 'Eine Tasche', ru: 'Сумку' },
          { de: 'Eine Halskette', ru: 'Ожерелье' },
          { de: 'Ein Kochbuch', ru: 'Кулинарную книгу' },
        ],
        correct: 2,
        explanation: 'В конце диалога решено: "okay, wenn es so ist, dann kaufen wir das Kochbuch" — они покупают кулинарную книгу.'
      }
    },
    {
      id: 'text-9', teil: 3, aufgabe: 13,
      name: 'Reise nach Berlin',
      type: 'планирование поездки',
      text: 'Ich freue mich schon auf unsere Reise nach Berlin. Ich auch. Wollen wir fliegen? Ach nee, zu teuer. Lass uns lieber mit dem Zug fahren. Fahren wir doch lieber mit dem Bus, ich glaube es ist billiger. Einverstanden. Dann müssen wir uns online über die Abfahrtszeiten informieren. Einverstanden, schauen wir gleich im Internet nach.',
      sentenceTranslations: {
        'Ich freue mich schon auf unsere Reise nach Berlin.': { literal: 'Я радую себя уже на нашу поездку в Берлин', literary: 'Я уже радуюсь нашей поездке в Берлин.' },
        'Ich auch.': { literal: 'Я тоже', literary: 'Я тоже.' },
        'Wollen wir fliegen?': { literal: 'Хотим мы лететь?', literary: 'Полетим?' },
        'Ach nee, zu teuer.': { literal: 'Ах нет, слишком дорого', literary: 'Ой нет, слишком дорого.' },
        'Lass uns lieber mit dem Zug fahren.': { literal: 'Позволь нам лучше поездом ехать', literary: 'Давай лучше поедем на поезде.' },
        'Fahren wir doch lieber mit dem Bus, ich glaube es ist billiger.': { literal: 'Едем мы же лучше автобусом, я думаю это есть дешевле', literary: 'Давай лучше поедем на автобусе, думаю, это дешевле.' },
        'Einverstanden.': { literal: 'Согласен', literary: 'Согласен.' },
        'Dann müssen wir uns online über die Abfahrtszeiten informieren.': { literal: 'Тогда должны мы себя онлайн о временах отправления информировать', literary: 'Тогда нам нужно узнать расписание в интернете.' },
        'Einverstanden, schauen wir gleich im Internet nach.': { literal: 'Согласен, посмотрим мы сразу в интернете', literary: 'Договорились, давай сразу посмотрим в интернете.' },
      },
      vocabulary: [
        { de: 'die Reise', plural: 'die Reisen', ru: 'поездка', gender: 'feminin', collocation: 'Reise nach Berlin', example: 'Ich freue mich schon auf unsere Reise nach Berlin.' },
        { de: 'der Zug', plural: 'die Züge', ru: 'поезд', gender: 'maskulin', collocation: 'mit dem Zug fahren', example: 'Lass uns lieber mit dem Zug fahren.' },
        { de: 'der Bus', plural: 'die Busse', ru: 'автобус', gender: 'maskulin', collocation: 'mit dem Bus fahren', example: 'Fahren wir doch lieber mit dem Bus.' },
        { de: 'die Abfahrtszeit', plural: 'die Abfahrtszeiten', ru: 'время отправления', gender: 'feminin', collocation: 'über Abfahrtszeiten informieren', example: 'Dann müssen wir uns online über die Abfahrtszeiten informieren.' },
        { de: 'sich freuen auf', ru: 'радоваться (предстоящему)', type: 'verb', forms: 'freut sich, freute sich, hat sich gefreut', example: 'Ich freue mich schon auf unsere Reise nach Berlin.' },
        { de: 'fliegen', ru: 'летать', type: 'verb', forms: 'fliegt, flog, ist geflogen', example: 'Wollen wir fliegen?' },
        { de: 'sich informieren über', ru: 'узнавать о', type: 'verb', forms: 'informiert sich, informierte sich, hat sich informiert', example: 'Dann müssen wir uns online über die Abfahrtszeiten informieren.' },
        { de: 'nachschauen', ru: 'посмотреть, проверить', type: 'verb', forms: 'schaut nach, schaute nach, hat nachgeschaut', example: 'Schauen wir gleich im Internet nach.' },
        { de: 'einverstanden', ru: 'согласен', type: 'adj', example: 'Einverstanden, schauen wir gleich im Internet nach.' },
      ],
      practiceSentences: [
        { de: 'Ich freue mich auf den Urlaub.', ru: 'Я радуюсь отпуску.', note: 'возвратный глагол на V2' },
        { de: 'Wollen wir ins Kino gehen?', ru: 'Пойдём в кино?', note: 'модальный V1 в вопросе' },
        { de: 'Lass uns Pizza essen!', ru: 'Давай поедим пиццу!', note: 'императив lass + uns + инфинитив' },
        { de: 'Wir müssen uns beeilen.', ru: 'Нам нужно поторопиться.', note: 'модальный + возвратный инфинитив' },
        { de: 'Ich schaue im Internet nach.', ru: 'Я посмотрю в интернете.', note: 'отделяемая приставка' },
      ],
      question: {
        de: 'Wie wollen sie nach Berlin fahren?',
        ru: 'Как они хотят ехать в Берлин?',
        options: [
          { de: 'Mit dem Flugzeug', ru: 'На самолёте' },
          { de: 'Mit dem Zug', ru: 'На поезде' },
          { de: 'Mit dem Bus', ru: 'На автобусе' },
        ],
        correct: 2,
        explanation: 'После обсуждения решают: "fahren wir doch lieber mit dem Bus, ich glaube es ist billiger" и "einverstanden" — они выбирают автобус.'
      }
    },
    {
      id: 'text-10', teil: 3, aufgabe: 14,
      name: 'Tante Anna',
      type: 'диалог о приезде',
      text: 'Wann kommt Tante Anna? Sonntag früh, holt sie Papa vom Bahnhof ab. Um wie viel Uhr kommt ihr Zug? Um 9 Uhr. Wie lange bleibt Tante Anna bei uns? Bis Dienstag, weil sie Donnerstag wieder arbeiten muss. Okay Mama, ich freue mich schon auf Tante Anna.',
      sentenceTranslations: {
        'Wann kommt Tante Anna?': { literal: 'Когда приезжает тётя Анна?', literary: 'Когда приедет тётя Анна?' },
        'Sonntag früh, holt sie Papa vom Bahnhof ab.': { literal: 'Воскресенье рано, забирает её папа с вокзала', literary: 'В воскресенье утром, папа заберёт её с вокзала.' },
        'Um wie viel Uhr kommt ihr Zug?': { literal: 'В сколько часов приходит её поезд?', literary: 'Во сколько прибывает её поезд?' },
        'Um 9 Uhr.': { literal: 'В 9 часов', literary: 'В 9 часов.' },
        'Wie lange bleibt Tante Anna bei uns?': { literal: 'Как долго остаётся тётя Анна у нас?', literary: 'Как долго тётя Анна пробудет у нас?' },
        'Bis Dienstag, weil sie Donnerstag wieder arbeiten muss.': { literal: 'До вторника, потому что она четверг снова работать должна', literary: 'До вторника, потому что в четверг ей снова нужно работать.' },
        'Okay Mama, ich freue mich schon auf Tante Anna.': { literal: 'Хорошо мама, я радуюсь уже на тётю Анну', literary: 'Хорошо, мама, я уже радуюсь приезду тёти Анны.' },
      },
      vocabulary: [
        { de: 'die Tante', plural: 'die Tanten', ru: 'тётя', gender: 'feminin', collocation: 'Tante Anna kommt', example: 'Wann kommt Tante Anna?' },
        { de: 'der Bahnhof', plural: 'die Bahnhöfe', ru: 'вокзал', gender: 'maskulin', collocation: 'vom Bahnhof abholen', example: 'Sonntag früh, holt sie Papa vom Bahnhof ab.' },
        { de: 'abholen', ru: 'забирать, встречать', type: 'verb', forms: 'holt ab, holte ab, hat abgeholt', example: 'Sonntag früh, holt sie Papa vom Bahnhof ab.' },
        { de: 'bleiben', ru: 'оставаться', type: 'verb', forms: 'bleibt, blieb, ist geblieben', example: 'Wie lange bleibt Tante Anna bei uns?' },
        { de: 'früh', ru: 'рано, утром', type: 'adv', example: 'Sonntag früh, holt sie Papa vom Bahnhof ab.' },
      ],
      practiceSentences: [
        { de: 'Wann kommt der Bus?', ru: 'Когда придёт автобус?', note: 'V2 после вопросительного слова' },
        { de: 'Morgen hole ich dich ab.', ru: 'Завтра я тебя заберу.', note: 'отделяемая приставка' },
        { de: 'Sie bleibt zwei Tage bei uns.', ru: 'Она пробудет у нас два дня.', note: 'bleibt на V2' },
        { de: 'Ich muss arbeiten, weil ich Geld brauche.', ru: 'Я должен работать, потому что мне нужны деньги.', note: 'глагол в конце weil-Satz' },
        { de: 'Um wie viel Uhr beginnt der Film?', ru: 'Во сколько начинается фильм?', note: 'V2 после вопроса' },
      ],
      question: {
        de: 'Bis wann bleibt Tante Anna zu Besuch?',
        ru: 'До какого дня тётя Анна остаётся в гостях?',
        options: [
          { de: 'Bis Montag', ru: 'До понедельника' },
          { de: 'Bis Dienstag', ru: 'До вторника' },
          { de: 'Bis Donnerstag', ru: 'До четверга' },
        ],
        correct: 1,
        explanation: 'На вопрос "wie lange bleibt Tante Anna bei uns?" отвечают: "bis Dienstag" — она остаётся до вторника.'
      }
    },
    {
      id: 'text-11', teil: 3, aufgabe: 15,
      name: 'Im Geschäft',
      type: 'покупка одежды',
      text: 'Entschuldigung, der blaue Pullover gefällt mir sehr. Gibt es ihn in Größe S? Leider nicht. Ich habe ihn nur in Größe M. In Größe S habe ich eine Bluse und noch dieses Kleid. Könnte ich bitte die Bluse sehen? Ja, gern, hier bitte. Ich habe Ihnen auch das Kleid mitgebracht, vielleicht gefällt es Ihnen. Beides sieht gut aus, aber die Bluse gefällt mir besser, ich nehme sie. Sehr schön.',
      sentenceTranslations: {
        'Entschuldigung, der blaue Pullover gefällt mir sehr.': { literal: 'Извинение, синий свитер нравится мне очень', literary: 'Извините, синий свитер мне очень нравится.' },
        'Gibt es ihn in Größe S?': { literal: 'Даётся его в размере S?', literary: 'Есть ли он в размере S?' },
        'Leider nicht.': { literal: 'К сожалению нет', literary: 'К сожалению, нет.' },
        'Ich habe ihn nur in Größe M.': { literal: 'Я имею его только в размере M', literary: 'У меня он есть только в размере M.' },
        'In Größe S habe ich eine Bluse und noch dieses Kleid.': { literal: 'В размере S имею я блузку и ещё это платье', literary: 'В размере S у меня есть блузка и вот это платье.' },
        'Könnte ich bitte die Bluse sehen?': { literal: 'Мог бы я пожалуйста блузку видеть?', literary: 'Можно посмотреть блузку?' },
        'Ja, gern, hier bitte.': { literal: 'Да, охотно, здесь пожалуйста', literary: 'Да, конечно, вот пожалуйста.' },
        'Ich habe Ihnen auch das Kleid mitgebracht, vielleicht gefällt es Ihnen.': { literal: 'Я имею вам также платье принёс, возможно нравится оно вам', literary: 'Я принёс вам и платье, может, оно вам понравится.' },
        'Beides sieht gut aus, aber die Bluse gefällt mir besser, ich nehme sie.': { literal: 'Оба выглядит хорошо, но блузка нравится мне лучше, я беру её', literary: 'И то, и другое хорошо выглядит, но блузка мне нравится больше, я её возьму.' },
        'Sehr schön.': { literal: 'Очень красиво', literary: 'Прекрасно.' },
      },
      vocabulary: [
        { de: 'der Pullover', plural: 'die Pullover', ru: 'свитер', gender: 'maskulin', collocation: 'der blaue Pullover', example: 'Entschuldigung, der blaue Pullover gefällt mir sehr.' },
        { de: 'die Größe', plural: 'die Größen', ru: 'размер', gender: 'feminin', collocation: 'in Größe S', example: 'Gibt es ihn in Größe S?' },
        { de: 'die Bluse', plural: 'die Blusen', ru: 'блузка', gender: 'feminin', collocation: 'die Bluse sehen', example: 'Könnte ich bitte die Bluse sehen?' },
        { de: 'das Kleid', plural: 'die Kleider', ru: 'платье', gender: 'neutrum', collocation: 'dieses Kleid', example: 'In Größe S habe ich eine Bluse und noch dieses Kleid.' },
        { de: 'gefallen', ru: 'нравиться', type: 'verb', forms: 'gefällt, gefiel, hat gefallen', example: 'Entschuldigung, der blaue Pullover gefällt mir sehr.' },
        { de: 'mitbringen', ru: 'приносить с собой', type: 'verb', forms: 'bringt mit, brachte mit, hat mitgebracht', example: 'Ich habe Ihnen auch das Kleid mitgebracht.' },
        { de: 'nehmen', ru: 'брать, покупать', type: 'verb', forms: 'nimmt, nahm, hat genommen', example: 'Die Bluse gefällt mir besser, ich nehme sie.' },
      ],
      practiceSentences: [
        { de: 'Der Rock gefällt mir gut.', ru: 'Юбка мне нравится.', note: 'gefällt на V2 с Dativ' },
        { de: 'Gibt es das in Rot?', ru: 'Есть это в красном?', note: 'безличная конструкция' },
        { de: 'Könnte ich das anprobieren?', ru: 'Можно это примерить?', note: 'Konjunktiv II для вежливости' },
        { de: 'Die Jacke sieht toll aus.', ru: 'Куртка выглядит отлично.', note: 'отделяемая приставка aussehen' },
        { de: 'Ich nehme beide Hemden.', ru: 'Я возьму обе рубашки.', note: 'nehme на V2' },
      ],
      question: {
        de: 'Was kauft die Kundin?',
        ru: 'Что покупает покупательница?',
        options: [
          { de: 'Den blauen Pullover in Größe M', ru: 'Синий свитер размера M' },
          { de: 'Die Bluse in Größe S', ru: 'Блузку размера S' },
          { de: 'Das Kleid', ru: 'Платье' },
        ],
        correct: 1,
        explanation: 'Покупательница говорит: "die Bluse gefällt mir besser, ich nehme sie" — она покупает блузку.'
      }
    },

    /* ═══ TEIL 4 — 1 длинное интервью ═══ */
    {
      id: 'text-12', teil: 4, aufgabe: 16,
      name: 'Interview Sebastian',
      type: 'интервью',
      text: 'Liebe Freunde, heute habe ich Sebastian Buchstein bei mir im Studio. Wir wollen uns über seine Pläne für die Zukunft unterhalten. Hallo Sebastian, guten Abend. Zunächst einmal herzlichen Glückwunsch zum Abitur. Du bist jetzt fertig mit dem Gymnasium und beginnst bald dein Studium, stimmt es? Ja, so ist es. Sag mal, wie war denn die Abschlussprüfung? Insgesamt war die Prüfung eigentlich gar nicht schwierig, nur in Mathe hatte ich Schwierigkeiten. Naja, trotzdem hast du dein Abitur mit sehr gut gemacht. Erzähl mal, was möchtest du studieren? Ich bin noch am Überlegen. Früher wollte ich Biologie studieren und Lehrer werden. Aber du hast deine Pläne geändert? Ja, ich möchte Medizin studieren und Arzt werden. Das dauert natürlich länger als ein Biologiestudium. Möchtest du nach dem Studium sofort arbeiten? Nein, ich möchte zuerst für ein Jahr ohne Bezahlung in Afrika tätig werden. Sobald ich damit fertig bin, werde ich mit dem Arbeiten beginnen. Das ist ein schöner Gedanke. Weißt du auch schon, wo du gern arbeiten möchtest? Am liebsten würde ich gerne im Katharina-Hospital arbeiten. Es ist in der Nähe von meinem Haus und ich kann zu Fuß hingehen. Ja, das wäre praktisch. Aber was machst du, wenn du keine Arbeitsstelle im Hospital bekommst? Dann bewerbe ich mich natürlich bei anderen Krankenhäusern, bis ich etwas finde, vielleicht in einer anderen Stadt. Also Sebastian, dann wünsche ich dir viel Erfolg und bedanke mich herzlich für dieses interessante Gespräch. Wir machen jetzt weiter mit Musik.',
      sentenceTranslations: {
        'Liebe Freunde, heute habe ich Sebastian Buchstein bei mir im Studio.': { literal: 'Дорогие друзья, сегодня имею я Себастьяна Бухштайна у меня в студии', literary: 'Дорогие друзья, сегодня у меня в студии Себастьян Бухштайн.' },
        'Wir wollen uns über seine Pläne für die Zukunft unterhalten.': { literal: 'Мы хотим себя о его планах на будущее поговорить', literary: 'Мы хотим поговорить о его планах на будущее.' },
        'Hallo Sebastian, guten Abend.': { literal: 'Привет Себастьян, добрый вечер', literary: 'Привет, Себастьян, добрый вечер.' },
        'Zunächst einmal herzlichen Glückwunsch zum Abitur.': { literal: 'Сначала однажды сердечное поздравление к абитуру', literary: 'Прежде всего, поздравляю с окончанием гимназии.' },
        'Du bist jetzt fertig mit dem Gymnasium und beginnst bald dein Studium, stimmt es?': { literal: 'Ты есть теперь готов с гимназией и начинаешь скоро твоё обучение, правильно это?', literary: 'Ты закончил гимназию и скоро начнёшь учёбу, правда?' },
        'Ja, so ist es.': { literal: 'Да, так есть это', literary: 'Да, именно так.' },
        'Sag mal, wie war denn die Abschlussprüfung?': { literal: 'Скажи-ка, как был же выпускной экзамен?', literary: 'Скажи, каким был выпускной экзамен?' },
        'Insgesamt war die Prüfung eigentlich gar nicht schwierig, nur in Mathe hatte ich Schwierigkeiten.': { literal: 'В целом был экзамен собственно совсем не трудный, только в математике имел я трудности', literary: 'В целом экзамен был не таким уж сложным, только с математикой были трудности.' },
        'Naja, trotzdem hast du dein Abitur mit sehr gut gemacht.': { literal: 'Ну, несмотря на это имеешь ты твой абитур с очень хорошо сделал', literary: 'Ну, всё равно ты сдал экзамены на отлично.' },
        'Erzähl mal, was möchtest du studieren?': { literal: 'Расскажи-ка, что хочешь ты изучать?', literary: 'Расскажи, что хочешь изучать?' },
        'Ich bin noch am Überlegen.': { literal: 'Я есть ещё при размышлении', literary: 'Я ещё думаю.' },
        'Früher wollte ich Biologie studieren und Lehrer werden.': { literal: 'Раньше хотел я биологию изучать и учителем стать', literary: 'Раньше я хотел изучать биологию и стать учителем.' },
        'Aber du hast deine Pläne geändert?': { literal: 'Но ты имеешь твои планы изменил?', literary: 'Но ты изменил свои планы?' },
        'Ja, ich möchte Medizin studieren und Arzt werden.': { literal: 'Да, я хочу медицину изучать и врачом стать', literary: 'Да, я хочу изучать медицину и стать врачом.' },
        'Das dauert natürlich länger als ein Biologiestudium.': { literal: 'Это длится конечно дольше чем биология-обучение', literary: 'Это, конечно, займёт больше времени, чем изучение биологии.' },
        'Möchtest du nach dem Studium sofort arbeiten?': { literal: 'Хочешь ты после обучения сразу работать?', literary: 'Ты хочешь сразу после учёбы работать?' },
        'Nein, ich möchte zuerst für ein Jahr ohne Bezahlung in Afrika tätig werden.': { literal: 'Нет, я хочу сначала на год без оплаты в Африке деятельным быть', literary: 'Нет, сначала я хочу год поработать в Африке без оплаты.' },
        'Sobald ich damit fertig bin, werde ich mit dem Arbeiten beginnen.': { literal: 'Как только я с этим готов есть, буду я с работой начинать', literary: 'Как только закончу с этим, начну работать.' },
        'Das ist ein schöner Gedanke.': { literal: 'Это есть красивая мысль', literary: 'Это прекрасная идея.' },
        'Weißt du auch schon, wo du gern arbeiten möchtest?': { literal: 'Знаешь ты также уже, где ты охотно работать хочешь?', literary: 'Ты уже знаешь, где хотел бы работать?' },
        'Am liebsten würde ich gerne im Katharina-Hospital arbeiten.': { literal: 'Охотнее всего бы я охотно в Катарина-госпитале работать', literary: 'Больше всего я хотел бы работать в больнице Катарины.' },
        'Es ist in der Nähe von meinem Haus und ich kann zu Fuß hingehen.': { literal: 'Оно есть в близости от моего дома и я могу пешком туда идти', literary: 'Она рядом с моим домом, и я могу ходить пешком.' },
        'Ja, das wäre praktisch.': { literal: 'Да, это было бы практично', literary: 'Да, это было бы удобно.' },
        'Aber was machst du, wenn du keine Arbeitsstelle im Hospital bekommst?': { literal: 'Но что делаешь ты, если ты никакое рабочее место в госпитале получишь?', literary: 'Но что будешь делать, если не получишь работу в этой больнице?' },
        'Dann bewerbe ich mich natürlich bei anderen Krankenhäusern, bis ich etwas finde, vielleicht in einer anderen Stadt.': { literal: 'Тогда подаю заявку я себя конечно в других больницах, пока я что-то найду, возможно в другом городе', literary: 'Тогда я буду подавать заявления в другие больницы, пока не найду что-нибудь, может, в другом городе.' },
        'Also Sebastian, dann wünsche ich dir viel Erfolg und bedanke mich herzlich für dieses interessante Gespräch.': { literal: 'Итак Себастьян, тогда желаю я тебе много успеха и благодарю себя сердечно за этот интересный разговор', literary: 'Что ж, Себастьян, желаю тебе успеха и сердечно благодарю за интересную беседу.' },
        'Wir machen jetzt weiter mit Musik.': { literal: 'Мы делаем сейчас дальше с музыкой', literary: 'Продолжаем с музыкой.' },
      },
      vocabulary: [
        { de: 'das Studio', plural: 'die Studios', ru: 'студия', gender: 'neutrum', collocation: 'bei mir im Studio', example: 'Liebe Freunde, heute habe ich Sebastian Buchstein bei mir im Studio.' },
        { de: 'der Plan', plural: 'die Pläne', ru: 'план', gender: 'maskulin', collocation: 'Pläne für die Zukunft', example: 'Wir wollen uns über seine Pläne für die Zukunft unterhalten.' },
        { de: 'die Zukunft', ru: 'будущее', gender: 'feminin', collocation: 'für die Zukunft', example: 'Wir wollen uns über seine Pläne für die Zukunft unterhalten.' },
        { de: 'das Abitur', plural: 'die Abiturs', ru: 'выпускной экзамен', gender: 'neutrum', collocation: 'Glückwunsch zum Abitur', example: 'Zunächst einmal herzlichen Glückwunsch zum Abitur.' },
        { de: 'das Gymnasium', plural: 'die Gymnasien', ru: 'гимназия', gender: 'neutrum', collocation: 'fertig mit dem Gymnasium', example: 'Du bist jetzt fertig mit dem Gymnasium.' },
        { de: 'das Studium', plural: 'die Studien', ru: 'учёба в вузе', gender: 'neutrum', collocation: 'dein Studium beginnen', example: 'Du bist jetzt fertig mit dem Gymnasium und beginnst bald dein Studium.' },
        { de: 'die Abschlussprüfung', plural: 'die Abschlussprüfungen', ru: 'выпускной экзамен', gender: 'feminin', collocation: 'die Abschlussprüfung', example: 'Sag mal, wie war denn die Abschlussprüfung?' },
        { de: 'die Schwierigkeit', plural: 'die Schwierigkeiten', ru: 'трудность', gender: 'feminin', collocation: 'Schwierigkeiten haben', example: 'Nur in Mathe hatte ich Schwierigkeiten.' },
        { de: 'die Medizin', ru: 'медицина', gender: 'feminin', collocation: 'Medizin studieren', example: 'Ich möchte Medizin studieren und Arzt werden.' },
        { de: 'der Arzt', plural: 'die Ärzte', ru: 'врач', gender: 'maskulin', collocation: 'Arzt werden', example: 'Ich möchte Medizin studieren und Arzt werden.' },
        { de: 'die Bezahlung', plural: 'die Bezahlungen', ru: 'оплата', gender: 'feminin', collocation: 'ohne Bezahlung', example: 'Ich möchte zuerst für ein Jahr ohne Bezahlung in Afrika tätig werden.' },
        { de: 'der Gedanke', plural: 'die Gedanken', ru: 'мысль, идея', gender: 'maskulin', collocation: 'ein schöner Gedanke', example: 'Das ist ein schöner Gedanke.' },
        { de: 'die Arbeitsstelle', plural: 'die Arbeitsstellen', ru: 'рабочее место', gender: 'feminin', collocation: 'keine Arbeitsstelle bekommen', example: 'Aber was machst du, wenn du keine Arbeitsstelle im Hospital bekommst?' },
        { de: 'das Krankenhaus', plural: 'die Krankenhäuser', ru: 'больница', gender: 'neutrum', collocation: 'bei Krankenhäusern bewerben', example: 'Dann bewerbe ich mich natürlich bei anderen Krankenhäusern.' },
        { de: 'der Erfolg', plural: 'die Erfolge', ru: 'успех', gender: 'maskulin', collocation: 'viel Erfolg', example: 'Dann wünsche ich dir viel Erfolg.' },
        { de: 'das Gespräch', plural: 'die Gespräche', ru: 'беседа, разговор', gender: 'neutrum', collocation: 'interessantes Gespräch', example: 'Bedanke mich herzlich für dieses interessante Gespräch.' },
        { de: 'sich unterhalten über', ru: 'беседовать о', type: 'verb', forms: 'unterhält sich, unterhielt sich, hat sich unterhalten', example: 'Wir wollen uns über seine Pläne für die Zukunft unterhalten.' },
        { de: 'studieren', ru: 'изучать (в вузе)', type: 'verb', forms: 'studiert, studierte, hat studiert', example: 'Ich möchte Medizin studieren und Arzt werden.' },
        { de: 'sich bewerben bei', ru: 'подавать заявление', type: 'verb', forms: 'bewirbt sich, bewarb sich, hat sich beworben', example: 'Dann bewerbe ich mich natürlich bei anderen Krankenhäusern.' },
        { de: 'schwierig', ru: 'трудный, сложный', type: 'adj', example: 'Insgesamt war die Prüfung eigentlich gar nicht schwierig.' },
        { de: 'praktisch', ru: 'удобный, практичный', type: 'adj', example: 'Ja, das wäre praktisch.' },
      ],
      practiceSentences: [
        { de: 'Ich bin fertig mit der Arbeit.', ru: 'Я закончил с работой.', note: 'bin на V2' },
        { de: 'Er möchte Lehrer werden.', ru: 'Он хочет стать учителем.', note: 'möchte + инфинитив' },
        { de: 'Wir unterhalten uns über das Wetter.', ru: 'Мы беседуем о погоде.', note: 'возвратный глагол на V2' },
        { de: 'Ich bewerbe mich bei der Firma.', ru: 'Я подаю заявление в фирму.', note: 'возвратный глагол' },
        { de: 'Sobald ich Zeit habe, rufe ich an.', ru: 'Как только у меня будет время, я позвоню.', note: 'глагол в конце придаточного' },
      ],
      question: {
        de: 'Was möchte Sebastian nach dem Abitur studieren?',
        ru: 'Что хочет изучать Себастьян после окончания гимназии?',
        options: [
          { de: 'Biologie', ru: 'Биологию' },
          { de: 'Medizin', ru: 'Медицину' },
          { de: 'Lehramt', ru: 'Педагогику' },
        ],
        correct: 1,
        explanation: 'Себастьян говорит: "ich möchte Medizin studieren und Arzt werden" — он хочет изучать медицину.'
      }
    },
  ],

  /* ─── промты ─── */
  prompts: {
    exercises: {
      instruction: 'Интерактивные упражнения работают прямо на сайте — выберите любое из списка ниже.',
      promptText: null,
    },
    original: {
      instruction: 'Оригинальная транскрипция аудио — все 12 мини-текстов по частям.',
      promptText: null,
    },
    translation: {
      instruction: 'Попредложный перевод всех мини-текстов (дословный + литературный). Используется для табa "Перевод".',
      promptText: null,
    },
    grammar: {
      instruction: 'Скопируй этот промт и вставь в Claude для пошагового перевода с грамматикой.',
      promptText: 'Ты — терпеливый преподаватель немецкого. Ученик уровня A2.\n\nТранскрипция аудирования (Goethe A2 Hören):\n{lessonText}\n\nЗадача: Разбери текст по предложениям.\n1. Покажи ОБРАЗЕЦ: разбери первое предложение по словам + грамматика\n2. Дай второе предложение — ученик переводит сам\n3. Правильный ответ = макс 2 строки: \"Genau! Дальше: [предложение]\"\n4. Ошибка = макс 4 строки: ❌→✓ + 1 фраза почему\n5. Мини-уроки грамматики каждые 3-4 предложения\n6. Темп > идеальность. Ученику интересно ДВИГАТЬСЯ.\n\nСловарь:\n{vocabularyList}\n\nНачни с Teil 1, Text 1 (Anna).',
    },
  },

  /* ─── grammarFocus ─── */
  grammarFocus: [
    'Модальные глаголы: will, möchte, müssen, können, wollen, sollen',
    'weil-Nebensatz: глагол в конце — weil sie Donnerstag wieder arbeiten muss',
    'dass-Nebensatz: dass das nicht richtig ist, dass ich nicht kommen konnte',
    'Отделяемые приставки: einladen, abholen, vorstellen, aussehen, nachschauen, mitbringen',
    'Perfekt с haben/sein: hat mitgebracht, hat getanzt, ist gekommen',
    'Konjunktiv II: würde ich essen, könnte ich sehen, das wäre praktisch',
    'wenn-Nebensatz: wenn du keine Arbeitsstelle bekommst',
    'Рефлексивные глаголы: sich freuen auf, sich unterhalten über, sich bewerben bei, sich informieren über',
    'es gibt + Akkusativ: es gibt Eis, gab es jede Menge Erfrischungsgetränke',
    'gefallen + Dativ: der Pullover gefällt mir, die Bluse gefällt mir besser',
  ],
};

LESSONS.push(LESSON_23);
